language: ruby
bundler_args: --without guard metrics
script: "bundle exec rake ci"
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
  - rbx
matrix:
  include:
    - rvm: jruby-19mode
    - rvm: jruby-20mode
    - rvm: jruby-21mode
    - rvm: jruby-head
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: 2.0.0
    - rvm: 2.1.0
    - rvm: rbx
  fast_finish: true
branches:
  only: master
notifications:
  email: false
